"""add active to products

Revision ID: f1bb61702cc1
Revises: 1ee41a019e73
Create Date: 2026-09-18 00:56:58.507981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1bb61702cc1'
down_revision: Union[str, Sequence[str], None] = '1ee41a019e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'produtos',
        sa.Column('active', sa.Boolean(), nullable=True)
    )

    op.execute("UPDATE produtos SET active = TRUE")

    op.alter_column(
        'produtos',
        'active',
        existing_type=sa.Boolean(),
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'active')
    # ### end Alembic commands ###
